# Generated by Django 4.1 on 2022-09-02 08:06

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(max_length=128)),
                ('Score', models.IntegerField()),
                ('Time_to_live', models.TimeField()),
                ('Passed_modules', django_mysql.models.ListCharField(models.CharField(max_length=11), max_length=132, size=11)),
            ],
        ),
    ]
