version: '3.7'

services:

    cyberpython:
        build:
            context: ./src/server/
            dockerfile: ./Dockerfile
            #we should modify the number of workers to be 16 when on master, 1 for debugging
        command: gunicorn --user www-data --workers 16 --timeout 120 --access-logfile /server/logs/gunicorn_access.log --error-logfile /server/logs/gunicorn_error.log --capture-output --log-level info --bind 0.0.0.0:8000 server.wsgi:application
        restart: always
        volumes:
            - ./logs/:/server/logs:rw
            - ./src/server:/server:rw
        depends_on:
            - db
            - migration
        deploy:
            replicas: 1
            
        secrets:
            - host_ssh_key
        # ports:              #this is for debbuging, should be commented on master
        #     - 19001:19001     #also this one should be closed on master  
          

    migration:
        build:
            context: ./src/server/
            dockerfile: ./Dockerfile
        command: >
            bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput&& ./update_modules_database.sh"
        volumes:
            - ./src/server:/server:rw
            - ./static:/server/static:rw

    nginx_server:
        build:
            context: ./src/nginx/
            dockerfile: ./Dockerfile
        ports:
            - "443:443"
        restart: always
        volumes:
            - ./logs/:/nginx/logs:rw
            - ./static:/static:rw
        depends_on:
            - cyberpython
    db:
        image: postgres:13
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"
    # pgadmin:
    #     image: dpage/pgadmin4
    #     environment:
    #         - PGADMIN_DEFAULT_EMAIL=admin@example.com
    #         - PGADMIN_DEFAULT_PASSWORD=admin123
    #     ports:
    #         - "8081:80"  # Expose pgAdmin on port 8080
volumes:
    static:
    postgres_data:


secrets:
    host_ssh_key:
        file: ~/.ssh/VulnDock
